### ISSUE TITLE
Moon becomes the exact same as daily moon

### ISSUE THREAD

**Issue by KaiWhen** [MaxWasUnavailable/MoonOfTheDay#1]
Played a lobby with friends where we did the daily moon, which was Experimentation. Later on (about one or two quotas later) we decided to go to Experimentation and it ended up being the exact same as the daily moon. I tested the same thing with the weekly moon (Vow) and it seemed fine, Vow had a different seed.
I haven't tested any further than that but I think it might be worth looking into.

**Comment by KaiWhen** [comment]
Looked into it more and seems moon seeds are being overridden by the daily seed after doing the daily moon. It's made it unplayable for me so would be great if it gets fixed!

**Comment by MaxWasUnavailable** [comment]
What is your mod list? Did you test this with *just* the MOTD mod?

**Comment by MaxWasUnavailable** [comment]
Resolved in 97ee334
