### ISSUE TITLE
It is not possible to select a Weekly Moon in the moons catalog with the "LethalExpansion" mod installed

### ISSUE THREAD

**Issue by oxota74** [MaxWasUnavailable/MoonOfTheDay#2]
![image](https://github.com/MaxWasUnavailable/MoonOfTheDay/assets/87602646/7b7ccbc5-6bcd-4675-9e47-0405ed235022)

**Comment by MaxWasUnavailable** [comment]
It seems Lethal Expansion might be overriding moons in a way that disallows other mods from adding their stuff without using their API. I'm not exactly willing to commit to one API over the dozen others that exist right now and do roughly the same thing, so this is something for the LE author to resolve.

**Comment by MaxWasUnavailable** [comment]
Please report this on their GitHub repo, here: https://github.com/HolographicWings/LethalExpansion

**Comment by HolographicWings** [comment]
I just saw this issue and i'm sorry for this compatibility issue
LE is not supposed to disallow moon addition from other mods, but the moon catalogue is overwritten to show all moons made with the SDK
I may look for a compatibility fix in the week
We might work together on it if you want @MaxWasUnavailable

**Comment by oxota74** [comment]
@HolographicWings Thank you for seeing this.

@MaxWasUnavailable I thought it was just a small problem, since the Daily Moon can be chosen, unlike the Weekly, which is strange.

**Comment by MaxWasUnavailable** [comment]
Reason seemed to have been a duplicate moon object name on my end. Resolved this in https://github.com/MaxWasUnavailable/MoonOfTheDay/commit/181ab08115fc6c5c966dc751d685d942c46e348b

Will publish an update sometime this week.
