### ISSUE TITLE
Future Support?

### ISSUE THREAD

**Issue by FrostyCirno** [MaxWasUnavailable/MoonOfTheDay#4]
I like the idea of this mod. Are you going to update it for and past v50?

**Comment by MaxWasUnavailable** [comment]
Did it break?

**Comment by FrostyCirno** [comment]
Sorry for the late response. I have one problem and one question. 
Problem : Trying to go to the weekly moon buys weed killer instead.
Question: Does this work with custom & moons added since it was last updated (Adamance, Artifice, Embrion)?

I am using the public beta.

**Comment by MaxWasUnavailable** [comment]
Re; Problem: Is this without any other mods?
Re; Question: Theoretically it should work with all moons, given they are added to the base game's moon list. In practice, though, it's likely some mods add their moons in special ways, or through frameworks that might take a different approach. So it's a bit of a coin toss.

**Comment by FrostyCirno** [comment]
This is with no other mods

**Comment by FrostyCirno** [comment]
Use https://thunderstore.io/c/lethal-company/p/SylviBlossom/TerminalConflictFix/

**Comment by MaxWasUnavailable** [comment]
Ah, that explains it. Thanks for the fix link! I don't currently have time to implement a workaround in the mod itself, but this is honestly probably a better fix than implementing something myself that might conflict with stuff like that.
